services:
  postgres:
    image: postgres
    env_file: postgres/.env
    volumes:
      - "db_data:/var/lib/postgres/data"
    networks:
      - default

  backend:
    build: .
    env_file:
      - sdapp/.env
      - postgres/.env
    ports:
      - "8000:80"
    volumes:
      - "./sdapp/static:/app/sdapp/static"
      - "./alembic:/app/alembic"
    networks:
      - default

  dramatiq:
    build:
      context: .
      dockerfile: ./Dockerfile

    command: "sh /dramatiq-entrypoint.sh"
    env_file: 
      - dramatiq/.env
      - sdapp/.env
      - postgres/.env

    volumes:
      - "./dramatiq/dramatiq-entrypoint.sh:/dramatiq-entrypoint.sh"
      - "./dramatiq/huggingface:/root/.cache/huggingface"
      - "./sdapp/static:/app/sdapp/static"
    networks:
      - default

  redis:
    image: redis
    networks:
      - default

volumes:
  db_data: 

networks:
  default:
    driver: "bridge"
